#=========================================================================
# ABOUT THIS FILE
#=========================================================================
# This file is used to add custom commands to BennerBot!
# Add commands in this format <name>: <command>, for example:
# IsCMD: Yes This Is a Command!     The previous can be used like so:
# !IsCmd, and the result will be: Yes This Is a Command!
# You can also use variables (our variables are bellow), you can also add
# a variable by adding a tilde (~) at the begging of a line, like so:
# ~username: JDBenner, it can then be used in a custom command like so:
# GetUserName: <username>, it will be displayed like so:
# !GetUserName, JDBenner
#=========================================================================
# BennerBot Variables
#=========================================================================
# <botname>: returns the name of the bot
# <botversion>: returns the version of the bot currently being used
# <twitchhost>: the name of the twitch channel this bot is managing
# <hitboxhost>: the name of the hitbox channel this bot is managing
# <username>: the name of the user who sent the command
#=========================================================================
#LEAVE THIS COMMAND
dummycommand: n/a
#You can add your commands here:
thisiscommand: cmd
~thisisvariable: var
usesvariable: <thisisvariable>
