#=======================
#General Settings
#=======================
#The name of the bot changing this has only an aesthetic effect
botName: BennerBot
#This determines the ID of the bot, bots using the same ID share settings
#set this to something specific to you or write this down somewhere
#leave this as default to let the bot handle this and use a default value specific to you.
botID: default
#Weather or not commands sent by the bot operator are phrased and responded to
respondToOperatorCommands: true
#how dates are displayed by the bot
#information on what this means can be found here: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
dateFormat: "HH:mm"
#weather or not names should be capitalized
capitalizeNames: false
#weather or not bennerbot should announce his presence
incognitoMode: true

#=======================
#API Integration Settings
#=======================
#weather or not to display a notification when someone follows
enableFollowerNotifications: true
#This allows you to use the !title and !game commands
enableStatusandGameUpdateing: true
#If you are running bennerbot on a server or a headless operating system set this if you want to use twitch api bassed features!
#this can be gotten here: "https://api.twitch.tv/kraken/oauth2/authorize?response_type=token&client_id=9qxushp3sdeasixpxajz8pqlxdudfs6&redirect_uri=http://localhost&scope=channel_editor+channel_subscriptions"
#when you authorize the bot it will redirect you to a black page, copy and past the access token from the url and paste it here!
twitchAccessToken: 

#=======================
#Twitch Settings
#=======================
#Weather or not to connect to a twitch channel
connectToTwitch: true
#The username of the the twitch account you want the bot to use
#Leave this to "default" if you dont want a custom account
#I recommend creating a new account for this
twitchUsername: default
#Enter the OAuth password (for lack of a better word) for your twitch account
#This can be found here: http://www.twitchapps.com/tmi/
#Leave this to "default" if you dont want a custom account
#I recommend creating a new account for this
twitchOAuth: default
#the name of the twitch account to moderate
twitchChannel: jdbener

#=======================
#Hitbox Settings
#=======================
#Weather or not to connect to a hitbox channel
connectToHitbox: true
#The username of the the hitbox account you want the bot to use
#Leave this to "default" if you dont want a custom account
#I recommend creating a new account for this
hitboxUsername: default
#Enter the password for your hitbox account
#Dont worry this wont be scene by anybody but yourself
#Leave this to "default" if you dont want a custom account
#I recommend creating a new account for this
hitboxPassword: default
#the name of the hitbox account to moderate
hitboxChannel: jdbener

#=======================
#Last.fm Settings
#=======================
#should last.fm intergation be enabled?
enableLastfmIntegration: false
#the username to get last.fm data about (please enclose in quotes, for example: "bennerbot")
lastfmName: 
#the format for how messages are responded to
#<user>: the user who sent the command
#<title>: the title of the song thats currently playing
#<artist>: the artist who performs said song
#<album>: the album that the song is realised on
#<url>: a link to find out more information about the song at
#add a number in front of these to represent previous tracks (number must be between 1 and 20)
#for example, <1title> would show the title of the previous song
songCommandMessageFormat: "hay <user> thats, <title> ~ <artist> on <album> <url>"
#songCommandMessageFormat: "hay <user> thats, <title> ~ <artist> on <album> <url>, the last song was: <1title> ~ <1artist>"
#The name for the !song command, 
lastfmCommandName: "!song"

#=======================
#Output Settings
#=======================
#weather or not to enable sending output to a file or a GUI
enableOutput: true
#weather or not to shorten usernames, 
#long names can cause issues and users names longer than 32 characters will be trimed no matter what
nameShortener: false
#Write the output to a clean file
#if output GUI is true this has to be true
WriteClean: true
#Write the output to a file that can be imported into obs
WriteDirty: true
#Weather or not to highlight messages that include your name in them
HighlighMessages: true
#Weather or not to display messages from "bennerbot"
enableBotMessages: true
#Weather or not user join messages will be displayed
enableJoinMessages: false
#Weather or not user leave messages will be displayed
enableLeaveMessages: false
#Weather or not messages that plugins create will be displayed
#I recommend leaving this off, some of these messages could get kinda "spammy"
enablePluginMessages: true
#weather or not to filter users whos names end in "bot"
filterBots: true
#weather or not to filter commands from messages
filterCommands: true
#The format for messages that are displayed in the GUI or Written to a file
#<server>: the server icon that this message is from
#<badge>: the moderator/streamer badge
#<timestamp>: the current time
#<color>: the color for a specific user
#<user>: the username of the user who sent the message, with his color added
#<noformateuser>: the username of the user who sent the message
#<message>: the message itself
DisplayMessageFormat: "<server> <badge><timestamp> <user>: <message>"

#=======================
#BennerBot Speech Settings
#=======================
#Weather or not bennerbot should read messages to you
enableTTS: false
#Weather or not to slightly change the pitch of a voice from message to message
enableVariability: false
#If this is enabled, only when a user sends a message the first time will the bot say the name of the sender
#This helps if you don't want the bot to read the name of a user when there is only one person talking
enableTTSMinimalisticMode: false
#Measured in words per minute... This determines how fast BennerBot Speaks
#default sounds best but may be hard to understand
#1-200 is slow or fast (1 is slow, 200 is super fast)
TTSSpeed: default
#how loud you want the bot to be on a scale of 1-10
TTSVolume: 10

#=======================
#Chat Moderation Settings
#=======================
#weather or not bennerbot should moderate your chat
#only set this to true if bennerbot has been modded on your channel
enableModeration: false
#How many warnings a user gets before being timed out
kickWarnings: 5
#How many warnings a user gets before being banned
banWarnings: 20
#Active Capitalazation Filter?
CapsFilter: true
#Activate message length Filtering
LengthFilter: true
#How what percentage of a message is required to be capitalized in order to activate the filter
#This is a decimal number where 1 = 100%
MaxCapsPercentage: .8
#The maximum length of a message
MaxMessageLength: 150

#=======================
#Relay Settings
#=======================
#weather or not the Chat Relay is activated
activateRelay: true
#weather or not to display the source of a message in the relay
showSource: false
#weather or not to display the username in the message for messages sent with the GUI
showSendName: false

#======================
#Auto Message Settings
#======================
#weather or not to enable the automessage system
enableAutoMessages: true
#the time in seconds between each method (60 seconds in a minute, 3600 seconds in an hour)
autoMessageInterval: 300

#======================
#Plugin System Settings
#======================
#weather or not to enable the Plugin System
enablePluginSystem: true